name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: ${{ github.repository }}-api
  IMAGE_NAME_WORKER: ${{ github.repository }}-worker

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          app/api-service/package-lock.json
          app/worker-service/package-lock.json

    - name: Install dependencies for API service
      run: |
        cd app/api-service
        npm ci

    - name: Run linting for API service
      run: |
        cd app/api-service
        npm run lint

    - name: Run tests for API service
      run: |
        cd app/api-service
        npm test

    - name: Install dependencies for Worker service
      run: |
        cd app/worker-service
        npm ci

    - name: Run linting for Worker service
      run: |
        cd app/worker-service
        npm run lint

    - name: Run tests for Worker service
      run: |
        cd app/worker-service
        npm test

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-projects --fail-on=all

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for API service
      id: meta-api
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Extract metadata for Worker service
      id: meta-worker
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WORKER }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push API service
      id: build-api
      uses: docker/build-push-action@v5
      with:
        context: ./app/api-service
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Worker service
      id: build-worker
      uses: docker/build-push-action@v5
      with:
        context: ./app/worker-service
        push: true
        tags: ${{ steps.meta-worker.outputs.tags }}
        labels: ${{ steps.meta-worker.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Print image digest for API service
      run: echo API Service Image Digest: ${{ steps.build-api.outputs.digest }}

    - name: Print image digest for Worker service
      run: echo Worker Service Image Digest: ${{ steps.build-worker.outputs.digest }}

  deploy-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/develop'
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DEV }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Dev using Kustomize
      run: |
        cd k8s/overlays/dev
        kustomize edit set image ghcr.io/${{ github.repository }}-api:${{ github.sha }}=ghcr.io/${{ github.repository }}-api:${{ github.sha }}
        kustomize edit set image ghcr.io/${{ github.repository }}-worker:${{ github.sha }}=ghcr.io/${{ github.repository }}-worker:${{ github.sha }}
        kubectl apply -k . --timeout=10m

    - name: Verify deployment in Dev
      run: |
        kubectl rollout status deployment/api-service-deployment -n dev --timeout=5m
        kubectl rollout status deployment/worker-service-deployment -n dev --timeout=5m
        kubectl get pods -n dev

  deploy-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_PROD }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Prod using Kustomize
      run: |
        cd k8s/overlays/prod
        kustomize edit set image ghcr.io/${{ github.repository }}-api:${{ github.sha }}=ghcr.io/${{ github.repository }}-api:${{ github.sha }}
        kustomize edit set image ghcr.io/${{ github.repository }}-worker:${{ github.sha }}=ghcr.io/${{ github.repository }}-worker:${{ github.sha }}
        kubectl apply -k . --timeout=10m

    - name: Verify deployment in Prod
      run: |
        kubectl rollout status deployment/api-service-deployment -n prod --timeout=5m
        kubectl rollout status deployment/worker-service-deployment -n prod --timeout=5m
        kubectl get pods -n prod

    - name: Run smoke tests on production
      run: |
        # Wait for services to be available
        sleep 30
        # Example: Check health endpoints
        API_POD=$(kubectl get pods -n prod -l app=api-service -o jsonpath='{.items[0].metadata.name}')
        kubectl exec $API_POD -n prod -- curl -f http://localhost:3000/health