name: Container Security Scan

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Mondays at 2 AM
  workflow_dispatch:

jobs:
  scan-images:
    name: Scan Container Images
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in image mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: 'ghcr.io/${{ github.repository }}-api:latest'
        format: 'sarif'
        output: 'trivy-api-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Run Trivy on Worker image
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: 'ghcr.io/${{ github.repository }}-worker:latest'
        format: 'sarif'
        output: 'trivy-worker-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-api-results.sarif'

    - name: Upload Trivy scan results for Worker
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-worker-results.sarif'